import React, { useState } from 'react';
import { Header } from '@/widgets/header/ui/Header';
import { Footer } from '@/widgets/footer/ui/Footer';

interface PropInfo {
  key: string;
  type: string;
  desc: string;
}

interface DocEntry {
  type: string;
  category: 'Declaration' | 'Expression' | 'Statement' | 'Literal' | 'Identifier';
  desc: string;
  example: string;
  properties: PropInfo[];
}

export const DocsPage: React.FC = () => {
  const [search, setSearch] = useState('');

  const docEntries: DocEntry[] = [
    {
      type: 'Identifier',
      category: 'Identifier',
      desc: 'Represents a variable, function, or property name. It is the basic naming component of an AST.',
      example: 'const userName = "Antigravity";\n// userName is an Identifier',
      properties: [
        { key: 'name', type: 'string', desc: 'The name of the identifier as a raw string.' },
      ],
    },
    {
      type: 'CallExpression',
      category: 'Expression',
      desc: 'Represents a function call expression, including the callee being called and the arguments array.',
      example: 'greet("Antigravity");\n// This entire line is a CallExpression',
      properties: [
        { key: 'callee', type: 'Expression', desc: 'The node representing the function being invoked.' },
        { key: 'arguments', type: 'Expression[]', desc: 'Array of arguments passed to the call.' },
      ],
    },
    {
      type: 'FunctionDeclaration',
      category: 'Declaration',
      desc: 'Declares a named function with parameter identifiers and a block statement containing body statements.',
      example: 'function add(a, b) {\n  return a + b;\n}',
      properties: [
        { key: 'id', type: 'Identifier', desc: 'The name of the declared function.' },
        { key: 'params', type: 'Pattern[]', desc: 'The list of parameters of the function.' },
        { key: 'body', type: 'BlockStatement', desc: 'The function body block.' },
      ],
    },
    {
      type: 'VariableDeclarator',
      category: 'Declaration',
      desc: 'Represents an individual variable declaration bind. It specifies the identifier being bound and optionally its initial value.',
      example: 'let count = 10;\n// count = 10 is the VariableDeclarator',
      properties: [
        { key: 'id', type: 'Pattern', desc: 'The variable name pattern (usually an Identifier).' },
        { key: 'init', type: 'Expression | null', desc: 'The initial value of the variable, or null if none.' },
      ],
    },
    {
      type: 'BinaryExpression',
      category: 'Expression',
      desc: 'Represents an expression with a binary operator, such as addition, subtraction, comparison, or equality checks.',
      example: 'const result = x + y;\n// x + y is the BinaryExpression',
      properties: [
        { key: 'operator', type: 'string', desc: 'The binary operator (e.g. "+", "-", "==", "===").' },
        { key: 'left', type: 'Expression', desc: 'The left side expression.' },
        { key: 'right', type: 'Expression', desc: 'The right side expression.' },
      ],
    },
    {
      type: 'IfStatement',
      category: 'Statement',
      desc: 'Represents a conditional control flow statement with a test expression, a consequent statement, and an optional alternate statement.',
      example: 'if (isActive) {\n  run();\n} else {\n  stop();\n}',
      properties: [
        { key: 'test', type: 'Expression', desc: 'The conditional test expression.' },
        { key: 'consequent', type: 'Statement', desc: 'The statement executed if the test passes.' },
        { key: 'alternate', type: 'Statement | null', desc: 'The statement executed if the test fails.' },
      ],
    },
  ];

  const filteredDocs = docEntries.filter(
    (doc) =>
      doc.type.toLowerCase().includes(search.toLowerCase()) ||
      doc.desc.toLowerCase().includes(search.toLowerCase()) ||
      doc.category.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="min-h-screen bg-[#0A0A12] flex flex-col text-[#F1F5F9] relative select-none">
      <Header />

      <main className="flex-1 max-w-4xl mx-auto px-6 py-12 w-full">
        {/* Header & Search */}
        <div className="mb-10 text-center md:text-left">
          <h1 className="text-4xl font-extrabold text-white mb-4">AST Node Reference</h1>
          <p className="text-[#94A3B8] mb-6">
            Glossary of common ESTree AST node types generated by the parser.
          </p>
          <div className="relative max-w-md mx-auto md:mx-0">
            <input
              type="text"
              placeholder="Search node types..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full bg-[#1C1C2E] border border-[#2A2A45] focus:border-[#06B6D4] text-white pl-10 pr-4 py-2.5 rounded-lg outline-none transition-colors text-sm"
            />
            <span className="absolute left-3.5 top-3.5 text-[#94A3B8]">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/>
              </svg>
            </span>
          </div>
        </div>

        {/* Entries list */}
        <div className="flex flex-col gap-6">
          {filteredDocs.length > 0 ? (
            filteredDocs.map((doc) => (
              <div key={doc.type} className="bg-[#12121F] border border-[#2A2A45] rounded-xl p-4 sm:p-6 flex flex-col gap-4 shadow-xl">
                {/* Title and Badge */}
                <div className="flex flex-col sm:flex-row sm:items-center justify-between border-b border-[#2A2A45] pb-3 gap-2">
                  <span className="font-mono text-lg sm:text-xl font-bold text-white bg-[#7C3AED]/10 border border-[#7C3AED]/20 px-2 py-0.5 rounded w-max">
                    {doc.type}
                  </span>
                  <span className={`text-[9px] sm:text-[10px] font-semibold px-2 py-0.5 rounded-full uppercase tracking-wider w-max ${
                    doc.category === 'Declaration' 
                      ? 'bg-[#7C3AED]/20 text-[#A855F7] border border-[#7C3AED]/30'
                      : doc.category === 'Expression'
                      ? 'bg-[#06B6D4]/20 text-[#06B6D4] border border-[#06B6D4]/30'
                      : doc.category === 'Statement'
                      ? 'bg-[#F59E0B]/20 text-[#F59E0B] border border-[#F59E0B]/30'
                      : doc.category === 'Literal'
                      ? 'bg-[#10B981]/20 text-[#10B981] border border-[#10B981]/30'
                      : 'bg-[#94A3B8]/20 text-[#94A3B8] border border-[#94A3B8]/30'
                  }`}>
                    {doc.category}
                  </span>
                </div>

                {/* Description */}
                <p className="text-[#F1F5F9] text-xs sm:text-sm leading-relaxed">{doc.desc}</p>

                {/* Code Example */}
                <div className="bg-[#0A0A12] border border-[#2A2A45] p-3 sm:p-4 rounded-lg font-mono text-[10px] sm:text-xs text-[#E2E8F0] overflow-x-auto">
                  <pre>{doc.example}</pre>
                </div>

                {/* Properties table */}
                <div className="overflow-x-auto border border-[#2A2A45] rounded-lg w-full">
                  <table className="w-full text-left text-[10px] sm:text-xs border-collapse min-w-[280px]">
                    <thead>
                      <tr className="bg-[#0D0D1A] border-b border-[#2A2A45] text-[#94A3B8]">
                        <th className="p-2 sm:p-3 font-semibold">Key</th>
                        <th className="p-2 sm:p-3 font-semibold">Type</th>
                        <th className="p-2 sm:p-3 font-semibold">Description</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-[#2A2A45] bg-[#12121F]">
                      {doc.properties.map((prop, idx) => (
                        <tr key={prop.key} className={idx % 2 === 0 ? 'bg-[#12121F]' : 'bg-[#0D0D1A]'}>
                          <td className="p-2 sm:p-3 font-mono text-[#F1F5F9] font-medium">{prop.key}</td>
                          <td className="p-2 sm:p-3 font-mono text-[#06B6D4]">{prop.type}</td>
                          <td className="p-2 sm:p-3 text-[#94A3B8] leading-relaxed">{prop.desc}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            ))
          ) : (
            <div className="text-center py-12 bg-[#12121F] border border-[#2A2A45] rounded-xl text-[#94A3B8]">
              No AST Node type matches your search.
            </div>
          )}
        </div>
      </main>

      <Footer />
    </div>
  );
};
export default DocsPage;
